### ISSUE TITLE
Error "The schema default is not configured"

### ISSUE THREAD

**Issue by hvoers** [ctrlo/Dancer2-Plugin-Auth-Extensible-Provider-DBIC#1]
Running 'plackup bin/app.psgi' I get "The schema default is not configured".

My config:
plugins:
  DBIC:
    providerdbic:
      schema_class: Providerdbic::Schema
      dsn: "dbi:SQLite:dbname=/home/henk/D2U/db/providerdbicdb"
  Auth::Extensible:
    login_page: '/login'
    exit_page: '/'
    realms:
      providerdbic:
        provider: 'DBIC'
        schema_name: 'providerdbic'

I do not want a schema named "default"...

**Comment by abeverley** [comment]
Thanks for this. Fixed in ca5d4c2750.

**Comment by hvoers** [comment]
Mmm. You invented a new name. Prior art uses "schema_name'.

**Comment by abeverley** [comment]
Okay, I'll revert and change it when I get a moment. Or you're welcome to create a PR yourself ;-)
