### ISSUE TITLE
remove README.pod from ..../Provider/

### ISSUE THREAD

**Issue by hvoers** [ctrlo/Dancer2-Plugin-Auth-Extensible-Provider-DBIC#11]
The README.pod is not a Provider.
Any other Provider should also do this.

**Comment by hvoers** [comment]
Maybe it's a FreeBSD ports tree problem.
The README.pod still end up in site_perl/Dancer2/Plugin/Auth/Extensible/Provider/README.pod

As long as no other Providers have a  README.pod this is not a big deal.

**Comment by SysPete** [comment]
Closed by e80dc17.
