### ISSUE TITLE
Result source names should be the only way to configure dbic

### ISSUE THREAD

**Issue by SysPete** [ctrlo/Dancer2-Plugin-Auth-Extensible-Provider-DBIC#12]
Using table names as a default is confusing and causes users to give up early. All other config styles should be deprecated.

**Comment by simbabque** [comment]
Discussion on IRC on 2017-01-02 about this issue:

> [12:51:59] \<SysPete> for #12 I'd like to see users_resultset and friends to be the only fully-documented way to configure resultset names
> [12:53:38] \<simbabque> so you want to drop the old stuff and remove the deprecation?
> [12:54:19] \<SysPete> atm only *_table are deprecated
> [12:54:46] \<SysPete> I'd like to make *_source deprecated too
> [12:55:35] \<SysPete> if those are specified we camelize them (read *guess*) to create the various *_resultset settings
> [12:55:58] \<SysPete> so for me *_resultset should be the only one of the 3 shown in the example config
> [12:56:40] \<SysPete> and the rest moved to a new section "DEPRECATED SETTINGS" and make sure warnings are thrown via deprecated_setting
> [12:57:04] \<simbabque> do you want me to do that?
> [12:57:14] \<SysPete> please go ahead

I'll do this in the next few days.
