### ISSUE TITLE
Random failures (hash randomization?)

### ISSUE THREAD

**Issue by eserte** [ctrlo/Dancer2-Plugin-Auth-Extensible-Provider-DBIC#18]
http://matrix.cpantesters.org/?dist=Dancer2-Plugin-Auth-Extensible-Provider-DBIC+0.623 shows random failures. As these happen only for perls >= 5.18.0 it is possible that the failures are caused by hash randomization (introduced to perl in version 5.17.6).

**Comment by tomhukins** [comment]
I think you're right.  I'm not certain, but I suspect https://github.com/PerlDancer/Dancer2-Plugin-Auth-Extensible/pull/87 might fix this.

**Comment by tomhukins** [comment]
I believe this ticket can be closed now, perhaps after updating the Makefile.PL dependency on `Dancer2::Plugin::Auth::Extensible` from `0.703` to `0.708`.

**Comment by abeverley** [comment]
Thanks all, I believe this is fixed as discussed.

**Comment by racke** [comment]
Well it needs a new release to be really fixed.

**Comment by abeverley** [comment]
> Well it needs a new release to be really fixed.

Currently queued with CPAN :)

**Comment by racke** [comment]
Good ... thanks for the fast processing of the pull requests.
