### ISSUE TITLE
Missing tests for this module

### ISSUE THREAD

**Issue by racke** [ctrlo/Dancer2-Plugin-Auth-Extensible-Provider-DBIC#3]

**Comment by SysPete** [comment]
I have a new branch with tests: https://github.com/SysPete/Dancer2-Plugin-Auth-Extensible-Provider-DBIC/tree/compat-plugin2-with-tests

This branch also works with plugin2 (assuming I don't find any further issues)

These tests work with latest upstream of the plugin itself: https://github.com/PerlDancer/Dancer2-Plugin-Auth-Extensible

**Comment by abeverley** [comment]
Awesome, thanks Pete. Will look at this over the weekend.

**Comment by abeverley** [comment]
Merged as #ebee743. Thanks @SysPete !
