### ISSUE TITLE
"make test" fails

### ISSUE THREAD

**Issue by hvoers** [ctrlo/Dancer2-Plugin-Auth-Extensible-Provider-DBIC#6]
Running "make test" gives me:

[snip lots of errors]

```
#   Failed test '/create_user response is 200'
#   at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 570.
#          got: '500'
#     expected: '200'

#   Failed test 'Login with newly created user succeeds'
#   at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 585.
#          got: '500'
#     expected: '302'
YAML Error: Expected separator '---'
   Code: YAML_PARSE_ERR_NO_SEPARATOR
   Line: 1
   Document: 2
 at /usr/local/lib/perl5/site_perl/YAML/Loader.pm line 80.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 84.
t/provider-dbic.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 35/84 subtests 

Test Summary Report
-------------------
t/provider-dbic.t (Wstat: 65280 Tests: 84 Failed: 35)
  Failed tests:  10-19, 21-23, 25-27, 45-46, 55-57, 59-60
                63, 65-66, 69, 71-73, 77, 79-82
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=1, Tests=84,  6 wallclock secs ( 0.16 usr  0.02 sys +  5.27 cusr  0.24 csys =  5.70 CPU)
Result: FAIL
Failed 1/1 test programs. 35/84 subtests failed.
*** [test_dynamic] Error code 255

Stop in /usr/ports/security/p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC/work/Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500.
*** [do-test] Error code 1

Stop in /usr/ports/security/p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC.
------------------------------------
```

What am I missing?

**Comment by racke** [comment]
Interesting, it works for me. Any idea where the YAML error comes from?

**Comment by hvoers** [comment]
On Wed, 20 Jan 2016, Stefan Hornburg (Racke) wrote:

> Interesting, it works for me. Any idea where the YAML error comes from?

Excuse my FreeBSD slang (p5- prefix)
I have installed the following YAMLs:

libyaml-0.1.6_2
p5-CPAN-Meta-YAML-0.018
p5-YAML-1.14
p5-YAML-LibYAML-0.59_1
p5-YAML-Tiny-1.67

What YAMLs do you have?

**Comment by abeverley** [comment]
The YAML error is because create_user is failing. YAML is used to get full details of a user. If the user wasn't created properly, then nothing will be returned and it can't be parsed (there is probably a better way of failing, but that's another subject).

Not sure whether it's related, but on the test results I'm seeing from CPAN testers, the BSD tests are failing because the cookie is not being set properly for some reason.

**Comment by abeverley** [comment]
@hvoers can you paste the full output of the failing tests please. We need what is effectively the backtrace.

**Comment by abeverley** [comment]
create_user is failing with a 500, so we need to know what's causing that.

**Comment by hvoers** [comment]
On Wed, 20 Jan 2016, Andy Beverley wrote:

> @hvoers can you paste the full output of the failing tests please. We need what is effectively the backtrace.

"script" output:

Script started on Wed Jan 20 10:28:11 2016
user@mbox:/usr/ports/security/p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC 

# make test

===>  License ART10 GPLv1 accepted by the user
===>   p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500 depends on file: /usr/local/sbin/pkg - found
===> Fetching all distfiles required by p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500 for building
===>  Extracting for p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500
=> SHA256 Checksum OK for Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500.tar.gz.
===>  Patching for p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500
===>   p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500 depends on package: p5-Dancer2>=0.166000 - found
===>   p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500 depends on package: p5-Dancer2-Plugin-Auth-Extensible>=0.500 - found
===>   p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500 depends on package: p5-Dancer2-Plugin-DBIC>=0.0011 - found
===>   p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500 depends on package: perl5>=5.20<5.21 - found
===>  Configuring for p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Dancer2::Plugin::Auth::Extensible::Provider::DBIC
Writing MYMETA.yml and MYMETA.json
===>  Building for p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500
cp README.pod blib/lib/Dancer2/Plugin/Auth/Extensible/Provider/README.pod
cp lib/Dancer2/Plugin/Auth/Extensible/Provider/DBIC.pm blib/lib/Dancer2/Plugin/Auth/Extensible/Provider/DBIC.pm
Manifying 2 pod documents
===>  Staging for p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500
===>   p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500 depends on package: p5-Dancer2>=0.166000 - found
===>   p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500 depends on package: p5-Dancer2-Plugin-Auth-Extensible>=0.500 - found
===>   p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500 depends on package: p5-Dancer2-Plugin-DBIC>=0.0011 - found
===>   p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500 depends on package: perl5>=5.20<5.21 - found
===>   Generating temporary packing list
Manifying 2 pod documents
Installing /usr/ports/security/p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC/work/stage/usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Provider/README.pod
Installing /usr/ports/security/p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC/work/stage/usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Provider/DBIC.pm
Installing /usr/ports/security/p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC/work/stage/usr/local/lib/perl5/site_perl/man/man3/Dancer2::Plugin::Auth::Extensible::Provider::README.3
Installing /usr/ports/security/p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC/work/stage/usr/local/lib/perl5/site_perl/man/man3/Dancer2::Plugin::Auth::Extensible::Provider::DBIC.3
====> Compressing man pages (compress-man)
====> Running Q/A tests (stage-qa)
===>  Testing for p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500
cd /usr/ports/security/p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC/work/Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500/ && /usr/bin/env XDG_DATA_HOME=/usr/ports/security/p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC/work  XDG_CONFIG_HOME=/usr/ports/security/p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC/work  HOME=/usr/ports/security/p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC/work NO_PIE=yes NO_DEBUG_FILES=yes SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  LIBDIR="/usr/lib"  CC="cc" CFLAGS="-O2 -pipe -fno-strict-aliasing"  CPP="cpp" CPPFLAGS=""  LDFLAGS="" LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-strict-aliasing"  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 444"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" /usr/bin/make DESTDIR=/usr/ports/security/p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC/work/stage test
PERL_DL_NONLAZY=1 "/usr/local/bin/perl5.20.3" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef _Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/_.t
t/provider-dbic.t .. t/provider-dbic.t .. 1/? 

# Failed test 'Login with real details succeeds'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 163.

# got: '500'

# expected: '302'

Use of uninitialized value $cookie in substitution (s///) at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 167.
Use of uninitialized value $cookie in concatenation (.) or string at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 168.

# Failed test 'Got the cookie: '

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 168.

# Failed test 'Can access /loggedin now we are logged in'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 177.

# got: '302'

# expected: '200'

# Failed test 'Correct page content while logged in, too'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 179.

# got: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

# <html xmlns="http://www.w3.org/1999/xhtml">

# <head>

# <title>Moved</title>

# </head>

# <body>

# <p>This item has moved <a href="http://localhost/login?return_url=%2Floggedin">here</a>.</p>

# </body>

# </html>

# '

# expected: 'You are logged in'

# Failed test 'Logged in user details via logged_in_user work'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 186.

# got: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

# <html xmlns="http://www.w3.org/1999/xhtml">

# <head>

# <title>Moved</title>

# </head>

# <body>

# <p>This item has moved <a href="http://localhost/login?return_url=%2Fname">here</a>.</p>

# </body>

# </html>

# '

# expected: 'Hello, David Precious'

# Failed test 'Correct roles for logged in user'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 194.

# got: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

# <html xmlns="http://www.w3.org/1999/xhtml">

# <head>

# <title>Moved</title>

# </head>

# <body>

# <p>This item has moved <a href="http://localhost/login?return_url=%2Froles">here</a>.</p>

# </body>

# </html>

# '

# expected: 'BeerDrinker,Motorcyclist'

# Failed test 'Correct roles for other user in current realm'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 201.

# got: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

# <html xmlns="http://www.w3.org/1999/xhtml">

# <head>

# <title>Moved</title>

# </head>

# <body>

# <p>This item has moved <a href="http://localhost/login?return_url=%2Froles%2Fbob">here</a>.</p>

# </body>

# </html>

# '

# expected: 'CiderDrinker'

# Failed test 'We can request a route (/beer) requiring a role we have...'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 210.

# got: '302'

# expected: '200'

# Failed test 'We can request a multi-role route requiring with any one role'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 220.

# got: '302'

# expected: '200'

# Failed test 'We can request a multi-role route with all roles required'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 227.

# got: '302'

# expected: '200'

# Failed test '/not_allroles redirected to denied page'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 235.

# got: 'http://localhost/login?return_url=%2Fnot_allroles'

# expected: 'http://localhost/login/denied?return_url=%2Fnot_allroles'

# Failed test 'We can request a regex route when logged in'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 249.

# got: '302'

# expected: '200'

# Failed test 'We can request a route requiring a regex role we have'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 255.

# got: '302'

# expected: '200'

# Failed test 'We cannot request a route requiring a role we don't have'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 267.

# got: 'http://localhost/login?return_url=%2Fpiss'

# expected: 'http://localhost/login/denied?return_url=%2Fpiss'

# Failed test 'Status code on /realm route.'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 277.

# got: '302'

# expected: '200'

# Failed test 'Authenticated against expected realm'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 278.

# got: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

# <html xmlns="http://www.w3.org/1999/xhtml">

# <head>

# <title>Moved</title>

# </head>

# <body>

# <p>This item has moved <a href="http://localhost/login?return_url=%2Frealm">here</a>.</p>

# </body>

# </html>

# '

# expected: 'config1'

 t/provider-dbic.t .. 45/? 

# Failed test 'Status code for login with return_url'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 411.

# got: '500'

# expected: '302'

# Failed test 'Redirect after login to given return_url works'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 413.

# got: undef

# expected: 'http://localhost/foobar'

# Failed test 'Login with real details succeeds'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 462.

# got: '500'

# expected: '302'

Use of uninitialized value $cookie in substitution (s///) at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 466.
Use of uninitialized value $cookie in concatenation (.) or string at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 467.

# Failed test 'Got the cookie: '

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 467.

# Failed test '/does_dave_drink_beer response is 200'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 475.

# got: '500'

# expected: '200'

# Failed test '/does_dave_drink_cider response is 200'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 480.

# got: '500'

# expected: '200'

# Failed test 'no way does dave drink cider'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 481.

# Failed test '/authenticate_user_with_realm_pass response is 200'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 493.

# got: '500'

# expected: '200'

# Failed test '/authenticate_user_with_realm_fail response is 200'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 499.

# got: '500'

# expected: '200'

# Failed test 'authentication failure'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 501.

# Failed test '/user_password?username=dave&password=beer response is 200'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 514.

# got: '500'

# expected: '200'

# Failed test '/user_password?username=dave&password=cider response is 200'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 520.

# got: '500'

# expected: '200'

# Failed test 'content shows fail'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 522.

# Failed test '/user_password?username=dave&password=beer&realm=config1 response is 200'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 527.

# got: '500'

# expected: '200'

# Failed test '/user_password?password=beer response is 200'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 540.

# got: '500'

# expected: '200'

# Failed test '/user_password?password=cider response is 200'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 546.

# got: '500'

# expected: '200'

# Failed test 'content shows fail'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 548.

# Failed test '/create_user response is 200'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 570.

# got: '500'

# expected: '200'

# Failed test 'Login with newly created user succeeds'

# at /usr/local/lib/perl5/site_perl/Dancer2/Plugin/Auth/Extensible/Test.pm line 585.

# got: '500'

# expected: '302'

 t/provider-dbic.t .. 83/? YAML Error: Expected separator '---'
    Code: YAML_PARSE_ERR_NO_SEPARATOR
    Line: 1
    Document: 2
  at /usr/local/lib/perl5/site_perl/YAML/Loader.pm line 80.

# Tests were run but no plan was declared and done_testing() was not seen.

# Looks like your test exited with 255 just after 84.

```
                        t/provider-dbic.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
```

Failed 35/84 subtests

## Test Summary Report

t/provider-dbic.t (Wstat: 65280 Tests: 84 Failed: 35)
   Failed tests:  10-19, 21-23, 25-27, 45-46, 55-57, 59-60
                 63, 65-66, 69, 71-73, 77, 79-82
   Non-zero exit status: 255
   Parse errors: No plan found in TAP output
Files=1, Tests=84,  6 wallclock secs ( 0.19 usr  0.01 sys +  5.23 cusr  0.29 csys =  5.72 CPU)
Result: FAIL
Failed 1/1 test programs. 35/84 subtests failed.
**\* [test_dynamic] Error code 255

Stop in /usr/ports/security/p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC/work/Dancer2-Plugin-Auth-Extensible-Provider-DBIC-0.500.
**\* [do-test] Error code 1

Stop in /usr/ports/security/p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC.
user@mbox:/usr/ports/security/p5-Dancer2-Plugin-Auth-Extensible-Provider-DBIC 

# ^Dexit

Script done on Wed Jan 20 10:28:35 2016

**Comment by abeverley** [comment]
Okay. It's failing way before the create_user problems. As per the problem on the cpan-testers output, there is a problem logging in on the "Login with real details succeeds" test. Can you see if you can find out why that is please? Again, it's returning a 500 when attempting to login.

There is some additional code required to dump the problem (sorry, I thought this happened automatically). If you add `or diag explain $trap->read;` to a failing test, then you will see a bunch of output, one of which will give the reason for the 500.

**Comment by hvoers** [comment]
On Wed, 20 Jan 2016, Andy Beverley wrote:

> There is some additional code required to dump the problem (sorry, I thought this happened automatically). If you add `or diag explain $trap->read;` to a failing test, then you will see a bunch of output, one of which will give the reason for the 500.

Mmm. I can not find a $trap in the "t" dir.

Is it in D2PAE ?

**Comment by abeverley** [comment]
Dancer2::Plugin::Auth::Extensible::Test

**Comment by SysPete** [comment]
This should be fixed by PR #7

**Comment by SysPete** [comment]
D2PAE tests updated to check response code after _every_ callback and if code is not expected then all logs since previous callback are displayed. @racke is cooking up a new D2PAE release so these will be in the wild pretty soon. I've tested PR #7 locally on FreeBSD 10.2 and this solves the issue there.

**Comment by racke** [comment]
D2PAE 0.501 release done.

**Comment by abeverley** [comment]
Provider::DBIC 0.501 released.

**Comment by SysPete** [comment]
Provider::DBIC 0.501 installed without issues using cpanminus on my FreeBSD 10.2 VM.

@hvoers can you confirm whether this issue is now fixed for you?

**Comment by SysPete** [comment]
Looking at cpantesters reports this has definitely been fixed by v0.501 so I think this issue can be closed.

**Comment by hvoers** [comment]
On Fri, 22 Jan 2016, Peter Mottram wrote:

> Looking at cpantesters reports this has definitely been fixed by v0.501 so I think this issue can be closed.

And v0.501 is on it's way as a new port to the FreeBSD ports-tree :)

Next: Passphrase support.

Shall we open a new issue?

**Comment by xsawyerx** [comment]
Guys, this is fantastic. I'm behind and I keep thinking "Oh wow, they discovered a problem! Oh wow, they found out why! Oh wow, they already fixed it and moved on! Oh wow, I'm behind!" :smile: 

@hvoers I think a new issue is a good idea.

If I can help in any way, please ping me. @hvoers, sorry you keep having to chase down issues, but I appreciate your persistence!

**Comment by SysPete** [comment]
@hvoers new issue opened for Passphrase support.

I'm closing this issue now since all problems are resolved.
