### ISSUE TITLE
Use Travis CI

### ISSUE THREAD

**Issue by racke** [ctrlo/Dancer2-Plugin-Auth-Extensible-Provider-DBIC#8]
This is a really useful tool which discovers problems on various perls based on a pristine setup.
Please use it for this project as well.

**Comment by abeverley** [comment]
Thanks racke. I've not used it before so will need to spend some (worthwhile) time learning it, and then I'll add it to this.

**Comment by racke** [comment]
It is quite simple.
- Get Travis account 
- Add Travis as Webservice for your repo  
- Read the Travis Absolute Beginners Guide 
- Use .travis.yml in D2PAE as example
- Don't forget to add .travis.yml to MANIFEST.SKIP

Regards
               Racke

**Comment by abeverley** [comment]
Thanks racke, will get that done.

**Comment by SysPete** [comment]
I'll add travis support once plugin2 is released.
